/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.lusxx.kotlin

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

class User(val name: String, val age: Int){
    override fun toString(): String {
        return "User (name=$name, age=$age)"
    }
}

//data class
data class  DataUser(val name:String, val age: Int) {
    fun intro () {
        println("Nama saya lusia $name")
        println("18 $age")
    }
}

fun main(args: Array<String>) {
    val user = User("lux",20)
    val dataUser = DataUser("lux", 22)

    println(user)
    println(dataUser)

    val (name, age) = dataUser
    println("Perkenalkan nama saya $name")
    println("18 $age")
    dataUser.intro()

    //collection
    val numberList = listOf(1, 2, 3, 4)
    println(numberList)
    println(numberList[1])

    //List
    val analyst = mutableListOf(1, "A", "Kotlin", true)
    analyst.add(4, false)
    analyst.add(5, "programming")
    println(analyst)

    //SET
    val integerSet = setOf(1,2,3,4,1,5)
    println(integerSet)

    val setA = setOf(1,2,3,4)
    val setB = setOf(4,3,1,2)
    println(setA == setB)

    val mutableSet = mutableSetOf(1,2,3,4,5)

    mutableSet.add(6)
    println(mutableSet)
    mutableSet.remove(4)
    println(mutableSet)


    //key-value
    //map
    val capital  = mapOf(
            "Jakarta" to "Indonesia",
            "London" to "England",
            "New Delhi" to "India"
    )
    println(capital["Jakarta"])
    println(capital["Kuala Lumpur"])
   // println(capital.getValue("Kuala Lumpur"))

    println(capital.keys)
    println(capital.values)

    val mutableCapital = capital.toMutableMap()

    mutableCapital.put("Kuala Lumpur", "Malaysia")

    println(mutableCapital)
}
